# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRatings',
            fields=[
                ('ratings_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ratings', models.IntegerField()),
                ('comments', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
                ('stall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Shop_particulars')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ratings', models.IntegerField()),
                ('comments', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
                ('stall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Shop_particulars')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=4)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('recommended_consume_time', models.CharField(max_length=100)),
                ('stall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Shop_particulars', verbose_name='Stall ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('order_qty', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('ord_status_cd', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ord_status_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.OrderStatus', verbose_name='Order Status ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='stall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Shop_particulars', verbose_name='Stall ID'),
        ),
    ]
